name: batedorbikes

services:
  app:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.batedorbikes.rule=Host(`batedorbikes.com.br`) || Host(`www.batedorbikes.com.br`)"
      - "traefik.http.routers.batedorbikes.entrypoints=websecure"
      - "traefik.http.routers.batedorbikes.tls.certresolver=le"
      - "traefik.http.services.batedorbikes.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - web

networks:
  web:
    external: true
